language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
  - php: nightly


## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - composer dumpautoload -o

script:
  - vendor/bin/php-cs-fixer fix .
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover